---
surname: Nathan G. Earley
position: "PhD Student"
address: "Victoria, British Columbia, Canada"
# profilepic: "./img/NateDTB2023_KaitlynDeiderichs.jpeg"
www: "earley-birder.github.io"
email: "nathan.g.earley@gmail.com"
github: earley-birder
orcid: 0000-0003-2835-9739
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: 990000
docname: CV
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)

require(xfun)

packages <- c('vitae'     # The CV's LaTeX Template
             ,'dplyr'     # For easier editing
             ,'tibble'    # Data structure for tribbles
             ,'magrittr'  # The Pipe %>%
             ,'here'      # Relative File Paths
             ,'readr'     # Data Loading
             ,'glue'      # String Manipulation
            )

xfun::pkg_attach2(packages, message = FALSE)

source(file = here("r","data.r"))

```


# Education

```{r EDUCATION}

edu %>%
  vitae::detailed_entries(
    with = degree,
    what = inst,
    why = detail,
    # when = glue::glue("{startMonth} {startYear} --> {endMonth} {endYear}"),
    when = case_when(
      !is.na(startMonth) & !is.na(startYear) & !is.na(endMonth) & !is.na(endYear) ~ glue::glue("{startMonth} {startYear} --> {endMonth} {endYear}"),
      !is.na(startMonth) & !is.na(startYear) & !is.na(endMonth) & is.na(endYear) ~ glue::glue("{startMonth} {startYear} --> {endMonth}"),
      !is.na(startYear) &  is.na(endYear) ~ glue::glue("{startMonth} {startYear}"),
      TRUE ~ ""
    ),
    where = where
  )

```

# Teaching Experience

```{r TEACHING}

tea %>%
  vitae::detailed_entries(
    with = position,
    what = course,
    why = detail,
    # when = glue::glue("{startMonth} {startYear} --> {endMonth} {endYear}"),
    when = case_when(
      !is.na(startYear) & !is.na(endYear) ~ glue::glue("{startMonth} {startYear} --> {endMonth} {endYear}"),
      !is.na(startYear) &  is.na(endYear) ~ glue::glue("{startMonth} {startYear}"),
      TRUE ~ ""
    ),
    where = inst
  )

```

\pagebreak
